### ISSUE TITLE
Which shard is at which node? It seems like all shards are on the same node.

### ISSUE THREAD

**Issue by ngominhhaibk** [qdrant/qdrant-helm#143]
I installed qdrant helm chart in cluster with 1 node master, 4 node workers and I created a collection with shard_number=2, replication_factor=2.
When I get cluster info with command: 
`curl http://192.168.1.168:31990/collections/test_collection_1/cluster # 6333:31990`
The results is:
```
{
   "result":{
      "peer_id":7901933018698687,
      "shard_count":2,
      "local_shards":[
         {
            "shard_id":0,
            "points_count":52505,
            "state":"Active"
         },
         {
            "shard_id":1,
            "points_count":47495,
            "state":"Active"
         }
      ],
      "remote_shards":[

      ],
      "shard_transfers":[

      ]
   },
   "status":"ok",
   "time":0.000017769
}
```
1. It's just get info about the number of shards, number of points in each shard, but I want to know which shard is on which node. It seems like all shards are on the same node. And I guess it's because the memory in other nodes not increase and I haven't run 2 command lines: 
```
./qdrant --uri 'http://qdrant_node_1:6335/'
./qdrant --bootstrap 'http://qdrant_node_1:6335/'
```
Are these commands run in the container? But how to access container in kubernetes (I tried "kubectl exec -it my-qdrant-demo sh", etc, but error: unable to upgrade connection: pod does not exist?)
If not, where are these commands run after install qdrant helm chart?

2. Why there is no any remote shard (backup)? Is it relate to pv/pvc ? (I'm using pv with hostPath /home/data in each node)

**Comment by connorNP** [comment]
If your qdrant pod isn't in the default namespace of your cluster, that command won't be able to find the pod. Specify the namespace in the command `"kubectl -n <namespace> exec -it my-qdrant-demo sh"`

**Comment by mac-chaffee** [comment]
Hi @ngominhhaibk , those `./qdrant` commands are not something you need to worry about since the helm chart configures those commands automatically when you increase the `replicaCount`.

As for the shards, by default all shards will stay on the original node (since "remote_shards" is empty, that means all your shards are on one node). Qdrant does not automatically move shards around between your nodes. Here are the docs about moving shards: https://qdrant.tech/documentation/guides/distributed_deployment/#making-use-of-a-new-distributed-qdrant-cluster

**Comment by ngominhhaibk** [comment]
Thank for all your helps. I resolved these problems.
