### ISSUE TITLE
Enhance auto-scaling with VerticalPodAutoscaler

### ISSUE THREAD

**Issue by clemlesne** [qdrant/qdrant-helm#41]
As of today, the application deployed scale horizontally (by adding more instances). It uses compute and overhead.

[In Kubernetes, we have the opportunity to scale the Pod vertically, with limits. The feature is called VerticalPodAutoscaler.](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#quick-start)

**Comment by M-Nawar** [comment]
Hi @clemlesne thanks a lot for your feedback, we are gonna work on adding this soon!

**Comment by mac-chaffee** [comment]
Hello, thanks for the suggestion! While I haven't personally tested it, I'm sure there would be no major issues to running the VPA against an installation of the Qdrant helm chart. The CustomResources for VPA will just need to be created outside of this helm chart.

My understanding is that as your workload scales, the VPA will occasionally recreate pods with different amounts of resources. When you `helm upgrade` this chart, the VPA has a mutatingwebhook which will adjust the resources to the correct values before any new pods are created. 

If you do use the VPA, I'd recommend setting `podDisruptionBudget.enabled: true` in the Qdrant helm chart to avoid downtime when scaling.

**Comment by aleecoveo** [comment]
👋 Does the VPA still work well if you use mmaps on your vectors? I think the VPA looks at the working set which doesn't include file caches, and I wonder if the VPA will then reduce the memory a lot so that hardly any part of the mmaped files are actually able to reside in memory, which will mean more disk reads and thus slower performance.
