### ISSUE TITLE
changing ownership of '/qdrant/storage': Operation not permitted

### ISSUE THREAD

**Issue by tekumara** [qdrant/qdrant-helm#82]
Using helm chart version 0.5.1 and the unprivileged image, qdrant fails to start because the `ensure-storage-dir-ownership` container fails with:
```
qdrant-0 ensure-storage-dir-ownership chown: changing ownership of '/qdrant/storage': Operation not permitted
```

**Comment by bashofmann** [comment]
@tekumara From the linked commit I can see that you set `image.tag=v1.5.1-unprivileged` in your values to use the unprivileged image.
Can you try using `image.useUnprivilegedImage=true` instead?
Both the init containers that ensure the correct volume permissions and the qdrant db container are using the same qdrant container image. But the init containers must run as root in order to be allowed to run `chown`. The `image.useUnprivilegedImage=true` should only use the unprivileged image for the Qdrant container and not for the init containers.

**Comment by tekumara** [comment]
Ah thank you @bashofmann using `image.useUnprivilegedImage=true` works!
